library(here)
library(tidyverse)

cat("=== VALIDATING classified_trajectories_processed FILES ===\n\n")
cat("These files are generated by 02c from the database.\n")
cat("We can validate if the subset reproduces the exact values from full database.\n\n")

# Load sampled cells
sampled_cells = read_csv(here("data", "processed", "sampled_grid_cells_50.csv"), 
                         show_col_types = FALSE)
cat("Sampled cells:", nrow(sampled_cells), "\n\n")

tolerance = 1e-10

# We need to compare against reference data from FULL database
# But we only have data from SUBSET database in data/processed/

cat("PROBLEM: data/processed/ contains outputs from 50-cell SUBSET database\n")
cat("We need outputs from FULL database for the same 50 cells to compare.\n\n")

cat("SOLUTION: Check if data/final files can tell us what to expect\n\n")

# The maps_regression files we extracted show what the final output should contain
ref_2015 = read_csv(here("data", "final_reference_50cells", "maps_regression_B_patches_2015_2040.csv"),
                    show_col_types = FALSE)
ref_2075 = read_csv(here("data", "final_reference_50cells", "maps_regression_B_patches_2075_2100.csv"),
                    show_col_types = FALSE)

cat("Reference from full database (filtered to 50 cells):\n")
cat("  2015-2040:", nrow(ref_2015), "patches\n")
cat("  2075-2100:", nrow(ref_2075), "patches\n\n")

# Check our classified trajectories
class_2015 = read_csv(here("data", "processed", "classified_trajectories_processed__2015_2040.csv"),
                      show_col_types = FALSE)
class_2075 = read_csv(here("data", "processed", "classified_trajectories_processed__2075_2100.csv"),
                      show_col_types = FALSE)

cat("Classified trajectories from 50-cell subset database:\n")
cat("  2015-2040:", nrow(class_2015), "patches\n")
cat("  2075-2100:", nrow(class_2075), "patches\n\n")

# The key question: do the (Lon, Lat, PID) match?
cat("Checking if (Lon, Lat, PID) combinations match...\n\n")

check_keys_match = function(ref_data, subset_data, label) {
  
  cat("===", label, "===\n")
  
  ref_keys = ref_data %>%
    distinct(Lon, Lat, PID) %>%
    arrange(Lon, Lat, PID)
  
  subset_keys = subset_data %>%
    distinct(Lon, Lat, PID) %>%
    arrange(Lon, Lat, PID)
  
  cat("  Reference (Lon, Lat, PID):", nrow(ref_keys), "\n")
  cat("  Subset (Lon, Lat, PID):   ", nrow(subset_keys), "\n")
  
  # Find matches
  matched = inner_join(ref_keys, subset_keys, by = c("Lon", "Lat", "PID"))
  only_in_ref = anti_join(ref_keys, subset_keys, by = c("Lon", "Lat", "PID"))
  only_in_subset = anti_join(subset_keys, ref_keys, by = c("Lon", "Lat", "PID"))
  
  cat("  Matched:          ", nrow(matched), "\n")
  cat("  Only in reference:", nrow(only_in_ref), "\n")
  cat("  Only in subset:   ", nrow(only_in_subset), "\n\n")
  
  if (nrow(only_in_ref) > 0) {
    cat("  Sample patches in reference but not subset:\n")
    print(head(only_in_ref, 5))
    cat("\n")
  }
  
  if (nrow(only_in_subset) > 0) {
    cat("  Sample patches in subset but not reference:\n")
    print(head(only_in_subset, 5))
    cat("\n")
  }
  
  return(list(matched = nrow(matched), 
              only_ref = nrow(only_in_ref),
              only_subset = nrow(only_in_subset)))
}

# Split classified data by scenario to match reference
class_2015_ssp585 = class_2015 %>% filter(s == "ssp585")
class_2075_ssp585 = class_2075 %>% filter(s == "ssp585")

result_2015 = check_keys_match(ref_2015, class_2015_ssp585, "2015-2040")
result_2075 = check_keys_match(ref_2075, class_2075_ssp585, "2075-2100")

cat("\n=== INTERPRETATION ===\n")
if (result_2015$only_ref == 0 && result_2015$only_subset == 0 &&
    result_2075$only_ref == 0 && result_2075$only_subset == 0) {
  cat("✓ PERFECT MATCH - All (Lon, Lat, PID) combinations match!\n")
  cat("  The subset database contains exactly the same patches as full database.\n")
  cat("  Now we can compare the actual VALUES (class, length_transient, etc.)\n")
} else {
  cat("⚠ MISMATCH - Different patches between reference and subset\n")
  cat("  This suggests the subset may have sampled different disturbance events.\n")
}
